### ISSUE TITLE
Some question about FID evaluation

### ISSUE THREAD

**Issue by mapengsen** [LTH14/rcg#35]
I see that you use the ADM assessment approach:

In ADM (https://github.com/openai/guided-diffusion/blob/main/evaluations/README.md)
![image](https://github.com/LTH14/rcg/assets/61998344/771d5b1e-59d2-43e0-a7f1-eede74df6775)

They say pre-computed statistics over the whole dataset, but when i load **ImageNet 256x256: [reference batch]**(https://openaipublic.blob.core.windows.net/diffusion/jul-2021/ref_batches/imagenet/256/VIRTUAL_imagenet256_labeled.npz)

![image](https://github.com/LTH14/rcg/assets/61998344/c44cabf7-09ba-4632-b5ad-da8672b7dbc2)

**but get 10000 image, not  whole dataset**, Is rcg also calculated in this way? I don't understand the 10000 here, could you please help me? Thank you very much!

**Comment by LTH14** [comment]
This also confused me for a while. In the ADM-precomputed reference batch, the pre-computed statistics for FID evaluation are just 'mu' and 'sigma'. The 10000 images in the batch are only for precision and recall computation, and not used for FID.

**Comment by mapengsen** [comment]
yes, 'mu', 'sigma', is easy to understand, but 'mu_s', 'sigma_s', don't know what it is? And how to calculate, they do not provide the relevant code.

**Comment by LTH14** [comment]
I remember it is for sFID.

**Comment by mapengsen** [comment]
I see. I am also confused here for a long time, really thank you very much :pray: :pray: :pray:
