### ISSUE TITLE
关于推理的部分

### ISSUE THREAD

**Issue by yanx57** [LTH14/rcg#38]
您好，很棒的工作。我对于rdm的部分比较感兴趣，看了rdm训练的代码，但是没有找到推理的代码，请问使用rdg根据condition输出推理特征的部分有吗？

**Comment by LTH14** [comment]
https://github.com/LTH14/rcg/blob/main/pixel_generator/mage/models_mage.py#L487-L501

**Comment by yanx57** [comment]
> https://github.com/LTH14/rcg/blob/main/pixel_generator/mage/models_mage.py#L487-L501

感谢
