### ISSUE TITLE
Distributed training question

### ISSUE THREAD

**Issue by QAQdev** [LTH14/rcg#39]
python -m torch.distributed.launch --nproc_per_node=8 --nnodes=8 --node_rank=0 \
main_ldm.py \
--config config/ldm/cin-ldm-vq-f8-repcond.yaml \
--batch_size 4 \
--epochs 40 \
--blr 2.5e-7 --weight_decay 0.01 \
--output_dir ${OUTPUT_DIR} \
--data_path ${IMAGENET_DIR} \
--dist_url tcp://${MASTER_SERVER_ADDRESS}:2214

I notice in the example script, `node_rank` is set to 0, why it is the same for all nodes? 🤔

**Comment by LTH14** [comment]
It should not be -- you should change it to the rank of each node accordingly.

**Comment by QAQdev** [comment]
thanks!
