### ISSUE TITLE
Extend 2D images input to 3D (2D stack) images input

### ISSUE THREAD

**Issue by QAQdev** [LTH14/rcg#40]
Hi, I want to apply rcg to 3D images, where 2D images are stacked. For example, a single 2D input can be (C, H, W), a 3D input is (V, C, H, W), where V is the volume size of the images.

I want to know what modules should be modified, to support 3D input and 3D generation (generating 2D stacked images)? 🤔 Let's assume we are working on DiT.

Looking forward to your reply!

**Comment by LTH14** [comment]
Check this patchemb https://github.com/LTH14/rcg/blob/main/pixel_generator/dit/models.py#L204. This convert a batch of bsz, C, H, W images into bsz, HxW, C; what you want (for bsz, C, V, H, W) is to modify this function so that it becomes bsz, VxHxW, C

**Comment by QAQdev** [comment]
> Check this patchemb https://github.com/LTH14/rcg/blob/main/pixel_generator/dit/models.py#L204. This convert a batch of bsz, C, H, W images into bsz, HxW, C; what you want (for bsz, C, V, H, W) is to modify this function so that it becomes bsz, VxHxW, C

I see. 
One more question, if I want to modify LDM to support 3D I/O, than means I should to change the conv2d to conv3d?

**Comment by LTH14** [comment]
Yes, in the LDM case you should change the UNet2D to UNet3D.

**Comment by QAQdev** [comment]
Thanks a lot!
