### ISSUE TITLE
Using concat as the conditioning key in LDM pixel generator

### ISSUE THREAD

**Issue by sgadgil6** [LTH14/rcg#43]
When I am trying to train the LDM pixel generator with `concat` as the conditioning key instead of the default `crossattn` as shown in https://github.com/LTH14/rcg/blob/main/config/ldm/cin-ldm-vq-f8-repcond.yaml, it errors out at [Line 1226](https://github.com/LTH14/rcg/blob/main/pixel_generator/ldm/models/diffusion/ddpm.py#L1226) since the number of dimensions of `x` and the `c_concat` condition representation are different. How do we fix this issue?

**Comment by LTH14** [comment]
I didn't implement the concat condition for LDM in this repo. You might need to refer to the original LDM codebase and see how they implemented it.

**Comment by sgadgil6** [comment]
Sounds good, thank you for the quick response

**Comment by sgadgil6** [comment]
I am trying to use LDM instead of MAGE as the pixel generator to do the interpolation experiment that you showed in Figure 7 of the paper but I am not getting good results by using `crossattn` conditioning. Did you happen to try that experiment with LDM?

**Comment by LTH14** [comment]
Unfortunately I only did the interpolation experiments on MAGE.
