### ISSUE TITLE
About crossattn in RDM

### ISSUE THREAD

**Issue by umnooob** [LTH14/rcg#5]
Thanks for your impressive work!

I notice that in the config and comments, `crossattn` is used for `context` to condition input. However, simply addition op is used in `ResBlock`. Any performance differences between them? 

And it would be nice if you could provide the original crossattn implementation.

**Comment by LTH14** [comment]
Thanks for your interest! I directly modify LDM's code for RDM, so there might be some legacy issues. Crossattn is not used in RDM.

**Comment by umnooob** [comment]
Thanks for your reply!
